### ISSUE TITLE
Urgent: Icon missing in translated results and pages

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_ubidb#37]
Hi
We've got the following bug reported:

Inside the search results:
http://dev.kommissionv8.netconsult.ch/de/ubi-datenbank/

and inside the detail view of the search results **the icon is missing in translated results** other than german. In german the icon appears but in the other languages it does not.

## # **Questions**

- Can you fix this issue (so that the icon appears in all languages) **at latest by October 20th 2017 evening**?
- Can you at the same time add the alt="" attribute for the icons with the corresponding text that is defined with them (the text is defined at the same place inside the extension where the icon is defined)?

If you can't fix this by October 20th, we have to arrange the development work as in the following week the customer is doing all the content integration so we can go live with the website. Please let me know if you have time to address this issue next week.

# Example 1 of the issue:

## **Search results in German:** The icons are visible. Everything okay.
> ![results-view-de](https://user-images.githubusercontent.com/1160557/31544820-fb55abca-b01c-11e7-8f20-fa69c3aeb49d.jpg)

## **Search results in french:** The icons are not visible.
> ![results-view-fr](https://user-images.githubusercontent.com/1160557/31544885-3f2edd4e-b01d-11e7-8c22-d2c072542118.jpg)

# Example 2:

## **Detail view of file "b.748" (only check this one) in german:** The icon is visible

> ![detailview-de](https://user-images.githubusercontent.com/1160557/31544922-767400b8-b01d-11e7-9051-822e6ae852bf.jpg)

## **Detail view of file "b.748" (only check this one) in french:** The icon is not visible
> ![detailview-fr](https://user-images.githubusercontent.com/1160557/31544934-8317e1cc-b01d-11e7-832a-321a488bc851.jpg)

If anything is not clear, I'm happy to answer your questions.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Greetings of the day!

**#Translation icon**
**Status**: Done
**Screenshots**: https://prnt.sc/gx91xl, https://prnt.sc/gx926r, https://prnt.sc/gx92d6

**Note**: We have spent **1.5 Hours** on this task. Can you please confirm?

Regards.
Regards.

**Comment by michelrossier** [comment]
Hello @jigneshnitsan 
Thanks for the fast reaction time, that's awesome. Although the icon issue was a bug, I confirm that.

In the results list the icon appears now in all languages! That is perfect.

What is **still missing is in "Example 2"** above on the detail page. There the icon is not correct localised yet.

What was not addressed is also this:

> - Can you at the same time add the alt="" attribute for the icons with the corresponding text that is defined with them (the text is defined at the same place inside the extension where the icon is defined)?

Thanks for your support!

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Greetings of the day!

Thank you for your message.

Please find the update as below.

**1.** What is still missing is in "Example 2" above on the detail page. There the icon is not correct localised yet.
**Status**: Done,
**Screenshots**: http://prntscr.com/gxyg8d , http://prntscr.com/gxygeg , http://prntscr.com/gxygm3

**2.** Can you at the same time add the alt="" attribute for the icons with the corresponding text that is defined with them (the text is defined at the same place inside the extension where the icon is defined)?
Status: Done
**Screenshots**: https://prnt.sc/gxydmx , https://prnt.sc/gxydzx , https://prnt.sc/gxyeb9

**@Estimation:** Thank you for your confirmation. Fyi, This project has been completed a long time ago and no longer in the support period. That's why we have given the estimation for the support.

Regards.

**Comment by michelrossier** [comment]
@jigneshnitsan 
Thanks that looks good!
